# Generated by Django 2.0.6 on 2018-11-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicfile', '0002_songs_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.ImageField(blank=True, upload_to='album_pic'),
        ),
    ]
