# Generated by Django 2.1.7 on 2019-02-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdultData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('workclass', models.CharField(choices=[('PR', 'Private'), ('SE', 'Self-emp-not-inc'), ('SEI', 'Self-emp-inc'), ('FG', 'Federal-gov'), ('LG', 'Local-gov'), ('SG', 'State-gov'), ('WP', 'Without-pay'), ('NW', 'Never-worked')], default='--select--', max_length=50)),
                ('fnl_wgt', models.IntegerField(default=0)),
                ('education', models.CharField(choices=[('BA', 'Bachelors'), ('SC', 'Some-college'), ('EL', '11th'), ('HSC', 'HS-grad'), ('PS', 'Prof-school'), ('AA', 'Assoc-acdm'), ('AV', 'Assoc-voc'), ('NI', '9th'), ('STE', '7th-8th'), ('TWE', '12th'), ('MS', 'Masters'), ('FTF', '1st-4th'), ('SSLC', '10th'), ('DR', 'Doctorate'), ('FTS', '5th-6th'), ('PS', 'Preschool')], default='--select--', max_length=50)),
                ('education_num', models.IntegerField(default=0)),
                ('maritalstatus', models.CharField(choices=[('MC', 'Married-civ-spouse'), ('DV', 'Divorced'), ('NM', 'Never-married'), ('SE', 'Separated'), ('WD', 'Widowed'), ('MSA', 'Married-spouse-absent'), ('MAS', 'Married-AF-spouse')], default='--select--', max_length=50)),
                ('occupation', models.CharField(choices=[('TS', 'Tech-support'), ('CR', 'Craft-repair'), ('OS', 'Other-service'), ('SA', 'Sales'), ('EM', 'Exec-managerial'), ('PS', 'Prof-specialty'), ('HC', 'Handlers-cleaners'), ('MOP', 'Machine-op-inspct'), ('AC', 'Adm-clerical'), ('FF', 'Farming-fishing'), ('TM', 'Transport-moving'), ('PHS', 'Priv-house-serv'), ('PS', 'Protective-serv'), ('AF', 'Armed-Forces')], default='--select--', max_length=50)),
                ('relationship', models.CharField(choices=[('Wife', 'Wife'), ('Own-child', 'Own-child'), ('Husband', 'Husband'), ('Not-in-family', 'Not-in-family'), ('Other-relative', 'Other-relative'), ('Unmarried', 'Unmarried')], default='--select--', max_length=50)),
                ('race', models.CharField(choices=[('WH', 'White'), ('API', 'Asian-Pac-Islander'), ('AIE', 'Amer-Indian-Eskimo'), ('OT', 'Other'), ('BL', 'Black')], default='--select--', max_length=50)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='--select--', max_length=50)),
                ('capital_gain', models.IntegerField(default=0)),
                ('capital_loss', models.IntegerField(default=0)),
                ('hours_per_week', models.IntegerField(default=0)),
                ('native_country', models.CharField(choices=[('US', 'United-States'), ('CAM', 'Cambodia'), ('UK', 'England'), ('PR', 'Puerto-Rico'), ('CA', 'Canada'), ('GER', 'Germany'), ('OUS', 'Outlying-US(Guam-USVI-etc)'), ('IND', 'India'), ('JAP', ' Japan'), ('GRE', 'Greece'), ('SO', 'South'), ('CHI', 'China'), ('CU', 'Cuba'), ('IR', 'Iran'), ('HO', 'Honduras'), ('PH', 'Philippines'), ('IT', 'Italy'), ('PL', 'Poland'), ('JAM', 'Jamaica'), ('VI', 'Vietnam'), ('MX', 'Mexico'), ('PO', 'Portugal'), ('IR', 'Ireland'), ('FR', 'France'), ('DR', 'Dominican-Republic'), ('LA', 'Laos'), ('ECU', 'Ecuador'), ('TAI', 'Taiwan'), ('HAI', 'Haiti'), ('COL', 'Columbia'), ('HUN', 'Hungary'), ('GUA', 'Guatemala'), ('NIC', 'Nicaragua'), ('SCO', 'Scotland'), ('THA', 'Thailand'), ('YUG', 'Yugoslavia'), ('EIS', 'El-Salvador'), ('TRI', 'Trinadad&Tobago'), ('PER', 'Peru'), ('HO', 'Hong'), ('HN', 'Holand-Netherlands')], default='--select--', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
